# Generated by Django 2.1.7 on 2020-05-16 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import voicetext.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('segment_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('voice_path', models.CharField(max_length=500)),
                ('status', models.IntegerField(choices=[(0, 'AVAILABLE'), (1, 'PROCESSING'), (2, 'PROCESSED'), (3, 'BLOCKED')], default=voicetext.models.StatusEnum(0))),
            ],
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('voice_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voice_note', models.CharField(max_length=500)),
                ('attempt', models.IntegerField(default=0)),
                ('segmented', models.BooleanField(default=False)),
                ('segment_count', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(0, 'AVAILABLE'), (1, 'PROCESSING'), (2, 'PROCESSED'), (3, 'BLOCKED')], default=voicetext.models.StatusEnum(3))),
                ('transcriber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voicetext', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='segment',
            name='voice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voiceid', to='voicetext.Voice'),
        ),
    ]
